FROM ghcr.io/maintaina/containers/groupware:php80-runtime

RUN zypper --non-interactive install --no-confirm php8-fpm \
    && zypper clean -a 

## TODO: Deploy fpm config
## TODO: Provide an entrypoint
## TODO: How to handle exposing static content to frontend server in different container?

EXPOSE 9000

