# syntax = docker/dockerfile:1.0-experimental
FROM ghcr.io/maintaina/containers/base:latest-runtime

WORKDIR /srv/www/horde

RUN --mount=type=secret,id=secrets,dst=/tmp/secrets.sh source /tmp/secrets.sh \
    && composer require horde/content ^3 horde/passwd ^6 horde/turba ^5 horde/kronolith ^5  horde/nag ^5 horde/mnemo ^5 \
    && composer clear-cache \
    && chown -R wwwrun:www /srv/www/horde/ \
    && unset COMPOSER_PAT

CMD ["/bin/bash"]
