# syntax = docker/dockerfile:1.0-experimental
FROM ghcr.io/maintaina/containers/base:latest-runtime

WORKDIR /srv/www/horde

RUN --mount=type=secret,id=secrets,dst=/tmp/secrets.sh source /tmp/secrets.sh \
    && composer --no-interaction require \
        horde/content "^3 || dev-FRAMEWORK_6_0" \
        horde/kronolith "^5 || dev-FRAMEWORK_6_0" \
        horde/mnemo "^5 || dev-FRAMEWORK_6_0" \
        horde/nag "^5 || dev-FRAMEWORK_6_0" \
        horde/passwd "^6 || dev-FRAMEWORK_6_0" \
        horde/turba "^5 || dev-FRAMEWORK_6_0" \
    && composer --no-interaction clear-cache \
    && chown -R wwwrun:www /srv/www/horde/ \
    && unset COMPOSER_PAT

CMD ["/bin/bash"]
