# syntax = docker/dockerfile:1.0-experimental
FROM docker.pkg.github.com/maintaina/containers/groupware:latest-runtime

WORKDIR /srv/www/horde

RUN --mount=type=secret,id=secrets,dst=/tmp/secrets.sh source /tmp/secrets.sh \
    && composer config repositories.pear pear "https://pear.php.net" \
    && composer require horde/imp horde/ingo \
    && composer clear-cache \
    && chown -R wwwrun:www /srv/www/horde \
    && unset COMPOSER_PAT

CMD ["/bin/bash"]
