FROM ghcr.io/maintaina/containers/groupware-webmail:php80-runtime

RUN zypper --non-interactive ref && zypper --non-interactive install --no-confirm apache2 apache2-utils apache2-mod_php8 \
    && zypper clean -a \
    && a2enmod mod_php8 \
    && a2enmod rewrite \
    && a2enflag SSL

COPY horde-vhost.conf /etc/apache2/vhosts.d/

EXPOSE 80
EXPOSE 443

CMD ["/usr/sbin/apache2ctl", "-DFOREGROUND"]
