FROM ghcr.io/maintaina/containers/base:latest-runtime

RUN zypper --non-interactive ref \
    && zypper --non-interactive install --no-confirm apache2 apache2-utils apache2-mod_php7 shadow fillup \
    && zypper clean -a \
    && a2enmod mod_php7 \
    && a2enmod rewrite ssl

COPY horde-vhost.conf /etc/apache2/vhosts.d/

EXPOSE 80
EXPOSE 443

CMD ["/usr/sbin/apache2ctl", "-DFOREGROUND"]
