FROM ghcr.io/maintaina/containers/base81:latest-runtime

RUN zypper --non-interactive ref \
    && zypper --non-interactive install --no-confirm apache2 apache2-utils apache2-mod_php8 shadow fillup \
    && zypper clean -a \
    && a2enmod mod_php8 \
    && a2enmod rewrite ssl \
    && a2enflag SSL

COPY horde-vhost.conf /etc/apache2/vhosts.d/

EXPOSE 80
EXPOSE 443

CMD ["/usr/sbin/apache2ctl", "-DFOREGROUND"]
